### ISSUE TITLE
Failed to run decompiliation command. Check your configuration. {"code":1,"type":"multi"} (Windows)

### ISSUE THREAD

**Issue by Vanadiom** [tintinweb/vscode-decompiler#13]
JDK is installed. The bin is in the PATH.

**Comment by tintinweb** [comment]
I assume you were trying to decompile java or apk?

can you provide me a list of error messages that are shown in the debug console? `command: toggle developer console`

**Comment by Vanadiom** [comment]
I don't know what I was doing anymore... Sorry!

**Comment by tintinweb** [comment]
feel free to reopen this issue if you run into this again.

**Comment by odyright** [comment]
Same issue for me! `Failed to run decompiliation command. Check your configuration. {"code":1,"type":"multi"}`
