### ISSUE TITLE
Cant decompile with Ghidra

### ISSUE THREAD

**Issue by K0IN** [tintinweb/vscode-decompiler#15]
Error Message after like 3 sec of running: configuration. {"code":1,"type":"single"}

[first message](https://i.imgur.com/vl4iOnM.png)
[error](https://i.imgur.com/z9nzfdi.png)
[settings](https://i.imgur.com/YDnTh3N.png)

I also ensured that ghirda works, and im on Windows 10 x64

Are my settings correct?

**Comment by Sympatron** [comment]
Same problem here.

**Comment by tintinweb** [comment]
what happens if you load that file directly in ghidra? does it also happen with other files? @K0IN @Sympatron

**Comment by K0IN** [comment]
Yes I can decompile it on ghidra without errors, it happens with all files (tested elf and exe)

could this be caused by the latest ghidra update?

also running windows 10 20H2 build 19042.685 (idk if this is useful)

**Comment by tintinweb** [comment]
@K0IN do you see any errors in the debug console? -> cmd -> toggle developer tools -> console
![image](https://user-images.githubusercontent.com/2865694/103015598-04c2d400-4541-11eb-9536-37bb88b9d882.png)

**Comment by K0IN** [comment]
does this help? https://i.imgur.com/IwnpT5W.png

**Comment by K0IN** [comment]
does this help? https://i.imgur.com/AqaXSTP.png

**Comment by tintinweb** [comment]
ok, looks like it works for ghidra 9.1.2 but it doesn't for ghidra 9.2.x. I think I have a fix for it. Are you down to trying an experimental vsix? @K0IN (I only tried it on osx)

**Comment by tintinweb** [comment]
published as v0.0.8. update your extension.

verified working on macos/win10 ghidra 9.2.1-public (and prevs. version 9.1.2 public).

thanks for reporting this issue @K0IN @Sympatron

**Comment by K0IN** [comment]
Sorry to bother you but it is still not possible to decompile Windows exe files -> elf file works fine tho

**Comment by tintinweb** [comment]
@K0IN it seems to work fine decompling an exe on macos or win10. 

If elf works and exe doesn't this may be a ghidra or path problem. e.g. does any of the paths involved contain spaces? Does it work if you decompile manually using ghidra?

(e.g. this is on macos with latest ghidra from homebrew)
![image](https://user-images.githubusercontent.com/2865694/103521015-5c820900-4e78-11eb-9939-a461b50308ce.png)
