### ISSUE TITLE
Failed to run decompiliation command. Check your configuration. {"code":1,"type":"single"}

### ISSUE THREAD

**Issue by TMZSeif** [tintinweb/vscode-decompiler#16]
I have installed ghidra and the jdk i have a windows computer and I have a jdk-16 pls help

**Comment by tintinweb** [comment]
Hey @TMZSeif,

what versions? did you configure the ghidra path as outlined in the readme? Is ghidra working when you run the batch file?

**Comment by CobaltAkaJames** [comment]
It would seem that the original poster is not returning to this any time soon, unfortunately. So, I'll provide you with my versions instead, since I have been experiencing the exact same problem. Visual Studio Code 1.55.2, Decompiler 0.0.8 and Ghidra 9.2.3

I have jdk 16 and a Windows 10 PC. I have the Ghidra path configured as was outlined in the ReadMe.

Ghidra works fine when running the batch file.

**Comment by tintinweb** [comment]
@CobaltAkaJames just checked it on a win10 with jdk 1.4 and ghidra 9.2.3 and it was working. can you share your configuration. are there any errors in the development console? does it also fail for different executables?

**Comment by CobaltAkaJames** [comment]
@tintinweb I'm not sure what else you are requesting in terms of configuration, if you could elaborate on that then perhaps I can provide further details. As for the development console, I can provide a text file copy of it if that would help. I'm a tad too inexperienced to be able to tell you what is definitively an error and what is not. And yes, it does fail for different executables.

**Comment by tintinweb** [comment]
so, ghidra headless does not seem to work with JDK 16. It is working though for JDK 14 when the os environment vars are set up correctly (which the JDK installer might not always do).

remove jdk 16 and install jdk 14 OR install jdk14 and make sure analyzeheadless is using the java env from jdk14. make sure JAVA_HOME and PATH are correctly set. I've also updated the readmes troubleshooting section with some more hints.

https://github.com/tintinweb/vscode-decompiler/commit/8ab1cdfda86361b90478e16cfd16956dbbd4bbb1


closing. not an extension issue. ghidra headless may not support jdk16. remove jdk16 install jdk14 ensure env vars are set correctly. follow readme + ghidra install guide.

cheers
