### ISSUE TITLE
How to decompile an apk using your tool?

### ISSUE THREAD

**Issue by agkick** [tintinweb/vscode-decompiler#18]
I'm very new on decompiling, tried several methods & tools.

I want to try yours since works on Visual Studio.

On the description you say that decompile: Android APK's, but I haven't been able to even open an apk on Visual Studio, I don't have any idea how to do it.

Do you have a tutorial in order to be able to use your tool?.

Your answer will be very appreciated

Thanks

**Comment by tintinweb** [comment]
Hi @agkick,

right-click -> decompile

![yx](https://user-images.githubusercontent.com/2865694/81797377-faeae400-950e-11ea-9060-2712dbb4740f.gif)
