### ISSUE TITLE
Trying to decompile dll throws exception

### ISSUE THREAD

**Issue by kadeler** [tintinweb/vscode-decompiler#21]
![image](https://user-images.githubusercontent.com/20907848/153732244-22ab9575-bd18-4802-89e8-5b9944f37ba8.png)
Path to idaw(but it's actually idat since 7.0)
![image](https://user-images.githubusercontent.com/20907848/153732267-8c9de5f7-3e53-4056-afd7-2bd627810c48.png)
if there's any debug info i can give lmk

**Comment by tintinweb** [comment]
hey @kadeler. I don't think `idat` is supported and I don't have a windows machine ready at hand. However, I've added more debug output to the latest version if you want to try again. please feel free to reopen this issue if the error persists. cheers.
