### ISSUE TITLE
Failed to run decompiliation command. Check your configuration. {"code":2,"type":"multi"}

### ISSUE THREAD

**Issue by ayhon** [tintinweb/vscode-decompiler#22]
I've run into similar issues where the JSON object is `{"code":1,"type":"multi"}` instead of what I got. Those errors seemed to be due to problems with the JDK. I have `java-11-openjdk` installed (Using Fedora 35), and get this error whenever I try to decompile a `jar` file. I have `jd-cli` installed, and reachable in the PATH.

**Comment by tintinweb** [comment]
hey @ayhon. error code 1 is pretty generic and jd-cli likely failed to decompile. I've added more debug output to the latest version if you want to try again. please feel free to reopen this issue if the error persists.  cheers.
