### ISSUE TITLE
File system provider for decompileFs

### ISSUE THREAD

**Issue by lguerard** [tintinweb/vscode-decompiler#26]
Hi,

I have installed this extension for testing something and uninstalled it since. Now I can't save a new file on it as I'm getting `File system provider for decompileFs:/%23%20-%2A-%20coding%3A%20utf-8%20-%2A-.py is not available.` everytime.

Also, the Decompiler! is still mentioned when looking at my workspaces in vscode (see screenshot)

![image](https://user-images.githubusercontent.com/6182107/187912794-419d48f3-10bb-4ab0-8c46-93a07359aa93.png)

Any ideas on how to fix this ? I tried reinstalling/uninstalling multiple times, removing the folder in ~/.vscode/extensions/ but still there..

Edit : Somehow, some files were still considered as using Decompiler even though computer and VSCode were restarted multiple times. Closing the workspace fixed the issue. Sorry for the trouble.

**Comment by sbreakey** [comment]
This should be re-opened and fixed. I installed it to test some java stuff, then uninstalled it, and it has broken the redhat java extensions ability to decompile. I shouldn't have to google to find this closed  ticket to figure out I have to close the workspace to fix it.
