### ISSUE TITLE
Decompilation fails on linux with ghidra, code 127

### ISSUE THREAD

**Issue by krk** [tintinweb/vscode-decompiler#3]
I have set the `vscode-decompiler.tool.ghidra.path` and `analyzeHeadless` script can find the JDK.

> Failed to run decompiliation command. Check your configuration. {"code":127,"type":"single"}

**Comment by tintinweb** [comment]
Hey @krk,

just tested it on Kali with `openjdk-11-jdk` and it works fine. 
![image](https://user-images.githubusercontent.com/2865694/82367891-d0b88b00-9a14-11ea-8153-97cbfb4f9d05.png)


The errorcode `127` is returned from the os and indicates that the command was not found. Please make sure that the configured path works fine (remove trailing spaces etc.). Here's my config: 

![image](https://user-images.githubusercontent.com/2865694/82368093-1ecd8e80-9a15-11ea-9c25-801c0d0b4e71.png)

Note that `analyzeHeadless` requires java11+ JDK to be installed.

**Comment by krk** [comment]
Thank you for the fast respone!

This is what I get when I enter a path that does not exist:
```
Failed to run decompiliation command. Check your configuration. {"code":{"errno":"ENOENT","code":"ENOENT","syscall":"spawn /home/krk/ghidra/analyzeHeadlesss","path":"/home/krk/ghidra/analyzeHeadlesss","spawnargs":["/tmp/tmp-22124-6oan5rCqS5VK","vscode-decompiler","-import","/home/krk/X","-scriptPath","/home/krk/.vscode/extensions/tintinweb.vscode-decompiler-0.0.4/scripts","-postscript","ghidra_decompile.py","/tmp/tmp-22124-SCC4h5mAaLaI"]},"type":"single"}
```

I get the shorter message when the path is correct and the bash script itself cannot find a path. I used a wrapper script for setting Java 11 path and that had an error in it, causing error 127. Now that it is fixed, decompiler works!
