### ISSUE TITLE
Decompile to multiple files?

### ISSUE THREAD

**Issue by NSExceptional** [tintinweb/vscode-decompiler#5]
Hey! First of all, awesome extension. Looking forward to Mac support for IDA Pro eventually!

Anyway, in the GIFs it looks like the entire binary's output goes into one file. Is that correct? If so, would it be possible to split the output into several files?

**Comment by tintinweb** [comment]
Hey @NSExceptional,

correct, IDA produces one pseudo-c file per executable (at least for PE/ELF). When would you split the file into multiple c-files?

ad IDA/macos: 
Unfortunately I don't have a *nix/mac version of IDA Pro at hand but would be happy to implement it. Did you try configuring the path to your local `<ida pro>/idal` binary in the config? Would you be able to test whether the following IDA extension works on macos? -> https://github.com/tintinweb/ida-batch_decompile? What is the `idaw` equivalent named under macos? (Linux -> `idal`).

cheers

**Comment by tintinweb** [comment]
closed -> inactive.
feel free to re-open if you feel like this is still an issue.
