### ISSUE TITLE
Getting errors trying to decompile with IDA Pro 6.6

### ISSUE THREAD

**Issue by b0-ones** [tintinweb/vscode-decompiler#6]
Edit: The solution provided works for Ghidra. Still having Problems getting IDA Pro to run.

Hi, I cant get the Extension to decompile any file. With both ghidra and IDA Pro I get different errors while trying to decompile calc.exe for example. Both Programs work on their own if I try to decompile the binary. Tried both 32 and 64 bit versions of IDA Pro.

Ghidra:
![grafik](https://user-images.githubusercontent.com/44143077/82681199-ba494400-9c4d-11ea-9442-5fc56acb13cc.png)

![grafik](https://user-images.githubusercontent.com/44143077/82681263-d351f500-9c4d-11ea-812b-7c91d88a119a.png)

IDA Pro:
![grafik](https://user-images.githubusercontent.com/44143077/82682017-dc8f9180-9c4e-11ea-999c-2484f80ec654.png)

![grafik](https://user-images.githubusercontent.com/44143077/82682039-e913ea00-9c4e-11ea-9493-ca6b8ec9dcb2.png)

Can you help me with what the errors mean? 

If I work from within ghidra/IDA Gui I can sucessfully produce .c-files. Would be cool to do this right inside VS Code. Any advice?

Thank you!

Additional Info:

Ghidra: 9.1.2 PUBLIC
IDA Pro: 6.6 
Java: AdoptOpenJDK - jdk-11.0.3.7-hotspot

![grafik](https://user-images.githubusercontent.com/44143077/82683453-5aed3300-9c51-11ea-8ed2-141d06e76914.png)

**Comment by tintinweb** [comment]
Hey @b0-ones,

Can you move ghidra to a path that does not contain a space like "Program Files" for a second and try again? I kind of suspect node's subprocess module doesn't like that.

Please let me know if that fixes the problem. I'll check out if there are any known issues with node and spaces in path's in the meantime.

**Comment by b0-ones** [comment]
Hello, that worked for Ghidra putting it in a Folder without spaces :)

![grafik](https://user-images.githubusercontent.com/44143077/82704453-d9f46280-9c75-11ea-99aa-445c8a581b8d.png)


How can I do that with IDA? Reinstall again in a different Location?

**Comment by tintinweb** [comment]
That node subprocess module is a mess when it comes to spaces in the path or args..

- Ghidra
  - ❌ win64 - space in path to ghidra; space in target filename
  - ✔️ win64 - space in path to ghidra; no space in target filename
  - ✔️ win64 - no space in path to ghidra; no space in target filename
  - ✔️ win64 - no space in path to ghidra; space in target filename
- Ida Pro
  - ❌ win64 - space in path to ida; space in target filename
  - ❌ win64 - space in path to ida; no space in target filename
  - ✔️ win64 - no space in path to ida; no space in target filename
  - ✔️ win64 - no space in path to ida; space in target filename

looking into a generic solution to fix this.

**Comment by b0-ones** [comment]
That command worked without an error and produced a calc.cpp file. 

![grafik](https://user-images.githubusercontent.com/44143077/82708674-22644e00-9c7f-11ea-9af0-fd8ea9132c7a.png)

But somehow I cant get it working with VS Code and this path:

C:\temp\IDA_6.6\test\calc.exe

and the binary in C:\temp\IDA_6.6\idaw.exe / idaw64.exe

I made "idaw" available in PATH and restartet vscode but still get this error:

![grafik](https://user-images.githubusercontent.com/44143077/82708855-9141a700-9c7f-11ea-84a9-de10b31a7f7f.png)

**Comment by tintinweb** [comment]
the error code 1 is actually what is returned by idaw. I therefore guess that it is not compatible with the script I am using (tested under 6.8). I can however add a fallback for this version.

**Comment by b0-ones** [comment]
it seems idaw64.exe -? (Version 6.6) produces the same output as:

https://www.hex-rays.com/products/ida/support/idadoc/417.shtml

![grafik](https://user-images.githubusercontent.com/44143077/82713754-6873de80-9c8c-11ea-9eff-07fcf26cd08e.png)
![grafik](https://user-images.githubusercontent.com/44143077/82713760-71fd4680-9c8c-11ea-8b99-d3cd66ab8a15.png)

**Comment by tintinweb** [comment]
@b0-ones 

yeah, looks like the decompiler python script does not seem to be compatible with your version. Added a couple of fixes and an experimental ida6.6 mode. Would you be able to test that?

**Comment by tintinweb** [comment]
@b0-ones, here's a debug package that 

* fixes the "spaces in path" problem
* fixes mixed line-endings when decompiling with ghidra on windows
* disables readonly on the decompiled sources
* adds a new default decompiler that should work with your version (it currently prints the cmdline as a warning box for you to verify). Let me know if that works.

![image](https://user-images.githubusercontent.com/2865694/82729587-174e0400-9cf9-11ea-90a5-81957e84cdfe.png)


the debug package is too large to be pasted here, therefore, please download https://wsi.li/LSXRVm2umBWHlV -> unzip -> check md5 (below) -> rename .png to .vsix -> `code --install-extension vscode-decompiler-0.0.5-0.0.6-debug-ida.vsix`

- try out the extension with ghidra in "Progam Files" or any folder that contains spaces
- try out the idea 6.6 legacy hexx plugin mode. Note: that I cannot test this mode as I don't have idea 6.6

MD5 (vscode-decompiler-0.0.5-0.0.6-debug-ida.vsix.png) = ba2b1933e609d242b50a9548a29a3a5a

**Comment by b0-ones** [comment]
I installed that .vsix, but I dont get the third option (legacy). Its also not in the package.json of that .vsix.

![grafik](https://user-images.githubusercontent.com/44143077/82730073-44041a80-9cfd-11ea-8217-e47aff5831ac.png)

Maybe you gave me the wrong version?

**Comment by tintinweb** [comment]
oh, if the warning msg doesn't pop up you're def. in an older version. let's try once again @b0-ones  :)  

repackage -> https://wsi.li/m1GxTFPbFQII81
MD5 (vscode-decompiler-0.0.5-debug-test.vsix) = 5684e26e9c532d93e74ccc2cbd516f86

**Comment by b0-ones** [comment]
Now thats better. I can see the debug information. I think there is a little error. There is no "-" infront of the "O".

![grafik](https://user-images.githubusercontent.com/44143077/82732725-5edf8a80-9d0f-11ea-8455-b92b24a56afa.png)

But if I try this command in console it doesnt produce a cpp-file (I created the AppData-Folder):
idaw64.exe -A -B -M Ohexx64:-new:C:\Users\Username\AppData\Local\Temp\tmp-6708-nhWuA0sjeb61\calc.exe.cpp:ALL "c:\temp\IDA_6.6\test\calc.exe"

If I do it manually and omit the "-B" and the "-M" and add "-" infront of "O" it still does not work.

What works is, if I dont give idaw64.exe the path to save the file, but instead let it save to the folder I am running the command in e.g. I am in folder "C:\temp" and do that command, I get the cpp-file in that folder (C:\temp\calc.exe.cpp):

idaw64.exe -A -Ohexx64:-new:calc.exe.cpp:ALL "c:\temp\IDA_6.6\test\calc.exe"

So maybe we need to pass the path to save the cpp-file somehow differently, so that it takes the path argument? But I didnt get it working till now to give that path-argument. I cant see the error of idaw64, the window closes so fast, I dont know how to pause it and see what it complains about...

**Comment by tintinweb** [comment]
give it a shot @b0-ones (uninstall the prevs. debug version first):

- Note: This method does not support IDA being in a path that contains spaces 🤷

https://wsi.li/9PRfM1Rw1oTetK
MD5 (vscode-decompiler-0.0.6.vsix) = b9946a2dda65f30225ed1790c7e2ee87

//PS. seems to work with ida 6.8 as well but is less reliable, produces db files in the target binary location (which is undesirable), may hang if db files are locked, ...

**Comment by tintinweb** [comment]
fixed & released. [v0.0.6](https://github.com/tintinweb/vscode-decompiler/releases/tag/v0.0.6)

**Comment by b0-ones** [comment]
> 
> 
> fixed & released. [v0.0.6](https://github.com/tintinweb/vscode-decompiler/releases/tag/v0.0.6)

thank you :)
